// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package matchingdata

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type Driverstatus string

const (
	DriverstatusAvailable Driverstatus = "available"
	DriverstatusOffline   Driverstatus = "offline"
	DriverstatusBusy      Driverstatus = "busy"
)

func (e *Driverstatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Driverstatus(s)
	case string:
		*e = Driverstatus(s)
	default:
		return fmt.Errorf("unsupported scan type for Driverstatus: %T", src)
	}
	return nil
}

type NullDriverstatus struct {
	Driverstatus Driverstatus
	Valid        bool // Valid is true if Driverstatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDriverstatus) Scan(value interface{}) error {
	if value == nil {
		ns.Driverstatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Driverstatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDriverstatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Driverstatus), nil
}

type Stream string

const (
	StreamRiderequested Stream = "ride.requested"
	StreamRidematching  Stream = "ride.matching"
	StreamRideaccepted  Stream = "ride.accepted"
)

func (e *Stream) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Stream(s)
	case string:
		*e = Stream(s)
	default:
		return fmt.Errorf("unsupported scan type for Stream: %T", src)
	}
	return nil
}

type NullStream struct {
	Stream Stream
	Valid  bool // Valid is true if Stream is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStream) Scan(value interface{}) error {
	if value == nil {
		ns.Stream, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Stream.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStream) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Stream), nil
}

type Deduplication struct {
	ID          pgtype.UUID
	RideID      pgtype.UUID
	Stream      Stream
	ProcessedAt pgtype.Timestamp
}

type Driver struct {
	ID     pgtype.UUID
	Name   string
	Status Driverstatus
}
