// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package matchingdata

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkDedupEntry = `-- name: CheckDedupEntry :one
SELECT id, ride_id, stream, processed_at FROM deduplication 
WHERE ride_id = $1 
    AND stream = $2
`

type CheckDedupEntryParams struct {
	RideID pgtype.UUID
	Stream Stream
}

func (q *Queries) CheckDedupEntry(ctx context.Context, arg CheckDedupEntryParams) (Deduplication, error) {
	row := q.db.QueryRow(ctx, checkDedupEntry, arg.RideID, arg.Stream)
	var i Deduplication
	err := row.Scan(
		&i.ID,
		&i.RideID,
		&i.Stream,
		&i.ProcessedAt,
	)
	return i, err
}

const createDedupEntry = `-- name: CreateDedupEntry :one
/* 
* Deduplication and Outbox
*/ 
INSERT INTO deduplication (
    ride_id, stream
) VALUES (
    $1, $2
) ON CONFLICT (
    ride_id, stream
) DO NOTHING
RETURNING id, ride_id, stream, processed_at
`

type CreateDedupEntryParams struct {
	RideID pgtype.UUID
	Stream Stream
}

func (q *Queries) CreateDedupEntry(ctx context.Context, arg CreateDedupEntryParams) (Deduplication, error) {
	row := q.db.QueryRow(ctx, createDedupEntry, arg.RideID, arg.Stream)
	var i Deduplication
	err := row.Scan(
		&i.ID,
		&i.RideID,
		&i.Stream,
		&i.ProcessedAt,
	)
	return i, err
}

const createDriver = `-- name: CreateDriver :one
INSERT INTO driver (
    name
) VALUES (
  $1
)
RETURNING id, name, status
`

func (q *Queries) CreateDriver(ctx context.Context, name string) (Driver, error) {
	row := q.db.QueryRow(ctx, createDriver, name)
	var i Driver
	err := row.Scan(&i.ID, &i.Name, &i.Status)
	return i, err
}

const createOutboxEvent = `-- name: CreateOutboxEvent :one
INSERT INTO outbox (
    ride_id, stream
) VALUES (
    $1, $2
) RETURNING id, ride_id, stream, created_at, retrieved_at, published_at
`

type CreateOutboxEventParams struct {
	RideID pgtype.UUID
	Stream NullStream
}

func (q *Queries) CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (Outbox, error) {
	row := q.db.QueryRow(ctx, createOutboxEvent, arg.RideID, arg.Stream)
	var i Outbox
	err := row.Scan(
		&i.ID,
		&i.RideID,
		&i.Stream,
		&i.CreatedAt,
		&i.RetrievedAt,
		&i.PublishedAt,
	)
	return i, err
}

const deleteDriver = `-- name: DeleteDriver :exec
DELETE FROM driver
WHERE id = $1
`

func (q *Queries) DeleteDriver(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDriver, id)
	return err
}

const getBusyDrivers = `-- name: GetBusyDrivers :many
/* 
    reconciler Queries
*/
SELECT id, name, status FROM driver
WHERE status = 'busy'
`

func (q *Queries) GetBusyDrivers(ctx context.Context) ([]Driver, error) {
	rows, err := q.db.Query(ctx, getBusyDrivers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Driver
	for rows.Next() {
		var i Driver
		if err := rows.Scan(&i.ID, &i.Name, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDriver = `-- name: GetDriver :one
/* 
* Driver
*/ 

SELECT id, name, status FROM driver
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetDriver(ctx context.Context, id pgtype.UUID) (Driver, error) {
	row := q.db.QueryRow(ctx, getDriver, id)
	var i Driver
	err := row.Scan(&i.ID, &i.Name, &i.Status)
	return i, err
}

const getNRandomAvailableDrivers = `-- name: GetNRandomAvailableDrivers :many
SELECT id, name, status FROM driver
WHERE status = 'available'
ORDER BY RANDOM()
LIMIT $1
`

func (q *Queries) GetNRandomAvailableDrivers(ctx context.Context, limit int32) ([]Driver, error) {
	rows, err := q.db.Query(ctx, getNRandomAvailableDrivers, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Driver
	for rows.Next() {
		var i Driver
		if err := rows.Scan(&i.ID, &i.Name, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRandomAvailableDriver = `-- name: GetRandomAvailableDriver :one
SELECT id, name, status FROM driver
WHERE status = 'available'
ORDER BY RANDOM()
LIMIT 1
`

func (q *Queries) GetRandomAvailableDriver(ctx context.Context) (Driver, error) {
	row := q.db.QueryRow(ctx, getRandomAvailableDriver)
	var i Driver
	err := row.Scan(&i.ID, &i.Name, &i.Status)
	return i, err
}

const listDrivers = `-- name: ListDrivers :many
SELECT id, name, status FROM driver
ORDER BY name
`

func (q *Queries) ListDrivers(ctx context.Context) ([]Driver, error) {
	rows, err := q.db.Query(ctx, listDrivers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Driver
	for rows.Next() {
		var i Driver
		if err := rows.Scan(&i.ID, &i.Name, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetAllDriversToAvailable = `-- name: ResetAllDriversToAvailable :exec
UPDATE driver
SET status = 'available'
`

func (q *Queries) ResetAllDriversToAvailable(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetAllDriversToAvailable)
	return err
}

const setDedupProcessed = `-- name: SetDedupProcessed :exec
UPDATE deduplication 
SET processed_at = NOW()
WHERE ride_id = $1 
    AND stream = $2
`

type SetDedupProcessedParams struct {
	RideID pgtype.UUID
	Stream Stream
}

func (q *Queries) SetDedupProcessed(ctx context.Context, arg SetDedupProcessedParams) error {
	_, err := q.db.Exec(ctx, setDedupProcessed, arg.RideID, arg.Stream)
	return err
}

const updateDriverStatus = `-- name: UpdateDriverStatus :exec
UPDATE driver
SET status = $2
WHERE id = $1
`

type UpdateDriverStatusParams struct {
	ID     pgtype.UUID
	Status Driverstatus
}

func (q *Queries) UpdateDriverStatus(ctx context.Context, arg UpdateDriverStatusParams) error {
	_, err := q.db.Exec(ctx, updateDriverStatus, arg.ID, arg.Status)
	return err
}
