// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package matchingdata

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDriver = `-- name: CreateDriver :one
INSERT INTO driver (
    name
) VALUES (
  $1
)
RETURNING id, name, status
`

func (q *Queries) CreateDriver(ctx context.Context, name string) (Driver, error) {
	row := q.db.QueryRow(ctx, createDriver, name)
	var i Driver
	err := row.Scan(&i.ID, &i.Name, &i.Status)
	return i, err
}

const deleteDriver = `-- name: DeleteDriver :exec
DELETE FROM driver
WHERE id = $1
`

func (q *Queries) DeleteDriver(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDriver, id)
	return err
}

const getDriver = `-- name: GetDriver :one
/* 
* Driver
*/ 

SELECT id, name, status FROM driver
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetDriver(ctx context.Context, id pgtype.UUID) (Driver, error) {
	row := q.db.QueryRow(ctx, getDriver, id)
	var i Driver
	err := row.Scan(&i.ID, &i.Name, &i.Status)
	return i, err
}

const getNRandomAvailableDrivers = `-- name: GetNRandomAvailableDrivers :many
SELECT id, name, status FROM driver
WHERE status = 'available'
ORDER BY RANDOM()
LIMIT $1
`

func (q *Queries) GetNRandomAvailableDrivers(ctx context.Context, limit int32) ([]Driver, error) {
	rows, err := q.db.Query(ctx, getNRandomAvailableDrivers, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Driver
	for rows.Next() {
		var i Driver
		if err := rows.Scan(&i.ID, &i.Name, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRandomAvailableDriver = `-- name: GetRandomAvailableDriver :one
SELECT id, name, status FROM driver
WHERE status = 'available'
ORDER BY RANDOM()
LIMIT 1
`

func (q *Queries) GetRandomAvailableDriver(ctx context.Context) (Driver, error) {
	row := q.db.QueryRow(ctx, getRandomAvailableDriver)
	var i Driver
	err := row.Scan(&i.ID, &i.Name, &i.Status)
	return i, err
}

const listDrivers = `-- name: ListDrivers :many
SELECT id, name, status FROM driver
ORDER BY name
`

func (q *Queries) ListDrivers(ctx context.Context) ([]Driver, error) {
	rows, err := q.db.Query(ctx, listDrivers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Driver
	for rows.Next() {
		var i Driver
		if err := rows.Scan(&i.ID, &i.Name, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetAllDriversToAvailable = `-- name: ResetAllDriversToAvailable :exec
UPDATE driver
SET status = 'available'
`

func (q *Queries) ResetAllDriversToAvailable(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetAllDriversToAvailable)
	return err
}

const updateDriverStatus = `-- name: UpdateDriverStatus :exec
UPDATE driver
SET status = $2
WHERE id = $1
`

type UpdateDriverStatusParams struct {
	ID     pgtype.UUID
	Status Driverstatus
}

func (q *Queries) UpdateDriverStatus(ctx context.Context, arg UpdateDriverStatusParams) error {
	_, err := q.db.Exec(ctx, updateDriverStatus, arg.ID, arg.Status)
	return err
}
