// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package ridedata

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type Ridestatus string

const (
	RidestatusUnspecified Ridestatus = "unspecified"
	RidestatusRequested   Ridestatus = "requested"
	RidestatusAccepted    Ridestatus = "accepted"
)

func (e *Ridestatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Ridestatus(s)
	case string:
		*e = Ridestatus(s)
	default:
		return fmt.Errorf("unsupported scan type for Ridestatus: %T", src)
	}
	return nil
}

type NullRidestatus struct {
	Ridestatus Ridestatus
	Valid      bool // Valid is true if Ridestatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRidestatus) Scan(value interface{}) error {
	if value == nil {
		ns.Ridestatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Ridestatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRidestatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Ridestatus), nil
}

type Stream string

const (
	StreamRiderequested Stream = "ride.requested"
	StreamRideaccepted  Stream = "ride.accepted"
)

func (e *Stream) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Stream(s)
	case string:
		*e = Stream(s)
	default:
		return fmt.Errorf("unsupported scan type for Stream: %T", src)
	}
	return nil
}

type NullStream struct {
	Stream Stream
	Valid  bool // Valid is true if Stream is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStream) Scan(value interface{}) error {
	if value == nil {
		ns.Stream, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Stream.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStream) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Stream), nil
}

type Deduplication struct {
	ID          pgtype.UUID
	RideID      pgtype.UUID
	Stream      Stream
	ProcessedAt pgtype.Timestamp
}

type Outbox struct {
	ID          pgtype.UUID
	RideID      pgtype.UUID
	Stream      Stream
	CreatedAt   pgtype.Timestamp
	RetrievedAt pgtype.Timestamp
	PublishedAt pgtype.Timestamp
}

type Requestdedup struct {
	Idempkey pgtype.UUID
	RideID   pgtype.UUID
}

type Ride struct {
	ID          pgtype.UUID
	RiderID     pgtype.UUID
	DriverID    pgtype.UUID
	RideStatus  Ridestatus
	RequestedAt pgtype.Timestamp
	AcceptedAt  pgtype.Timestamp
}
