// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package ridedata

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type Ridestatus string

const (
	RidestatusUnspecified Ridestatus = "unspecified"
	RidestatusRequested   Ridestatus = "requested"
	RidestatusMatching    Ridestatus = "matching"
	RidestatusMatched     Ridestatus = "matched"
	RidestatusAccepted    Ridestatus = "accepted"
	RidestatusInProgress  Ridestatus = "in_progress"
	RidestatusCompleted   Ridestatus = "completed"
	RidestatusCancelled   Ridestatus = "cancelled"
	RidestatusFailed      Ridestatus = "failed"
)

func (e *Ridestatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Ridestatus(s)
	case string:
		*e = Ridestatus(s)
	default:
		return fmt.Errorf("unsupported scan type for Ridestatus: %T", src)
	}
	return nil
}

type NullRidestatus struct {
	Ridestatus Ridestatus
	Valid      bool // Valid is true if Ridestatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRidestatus) Scan(value interface{}) error {
	if value == nil {
		ns.Ridestatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Ridestatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRidestatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Ridestatus), nil
}

type Ride struct {
	ID          pgtype.UUID
	RiderID     pgtype.UUID
	DriverID    pgtype.UUID
	RideStatus  Ridestatus
	RequestedAt pgtype.Timestamp
	MatchingAt  pgtype.Timestamp
	MatchedAt   pgtype.Timestamp
	AcceptedAt  pgtype.Timestamp
}
