// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package ridedata

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRide = `-- name: CreateRide :one
INSERT INTO ride (
  id, rider_id
) VALUES (
  $1, $2
)
RETURNING id, rider_id, driver_id, ride_status, requested_at, matching_at, matched_at, accepted_at
`

type CreateRideParams struct {
	ID      pgtype.UUID
	RiderID pgtype.UUID
}

func (q *Queries) CreateRide(ctx context.Context, arg CreateRideParams) (Ride, error) {
	row := q.db.QueryRow(ctx, createRide, arg.ID, arg.RiderID)
	var i Ride
	err := row.Scan(
		&i.ID,
		&i.RiderID,
		&i.DriverID,
		&i.RideStatus,
		&i.RequestedAt,
		&i.MatchingAt,
		&i.MatchedAt,
		&i.AcceptedAt,
	)
	return i, err
}

const deleteRide = `-- name: DeleteRide :exec
DELETE FROM ride
WHERE id = $1
`

func (q *Queries) DeleteRide(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRide, id)
	return err
}

const getRide = `-- name: GetRide :one
/* 
* Ride
*/ 

SELECT id, rider_id, driver_id, ride_status, requested_at, matching_at, matched_at, accepted_at FROM ride
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetRide(ctx context.Context, id pgtype.UUID) (Ride, error) {
	row := q.db.QueryRow(ctx, getRide, id)
	var i Ride
	err := row.Scan(
		&i.ID,
		&i.RiderID,
		&i.DriverID,
		&i.RideStatus,
		&i.RequestedAt,
		&i.MatchingAt,
		&i.MatchedAt,
		&i.AcceptedAt,
	)
	return i, err
}

const getStaleRidesByStatus = `-- name: GetStaleRidesByStatus :many
/* 
    Reconciliation Queries
*/
SELECT id, rider_id, driver_id, ride_status, requested_at, matching_at, matched_at, accepted_at FROM ride
WHERE ride_status = $1
  AND requested_at < NOW() - INTERVAL '1 second' * $2
`

type GetStaleRidesByStatusParams struct {
	RideStatus Ridestatus
	Column2    interface{}
}

func (q *Queries) GetStaleRidesByStatus(ctx context.Context, arg GetStaleRidesByStatusParams) ([]Ride, error) {
	rows, err := q.db.Query(ctx, getStaleRidesByStatus, arg.RideStatus, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ride
	for rows.Next() {
		var i Ride
		if err := rows.Scan(
			&i.ID,
			&i.RiderID,
			&i.DriverID,
			&i.RideStatus,
			&i.RequestedAt,
			&i.MatchingAt,
			&i.MatchedAt,
			&i.AcceptedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRides = `-- name: ListRides :many
SELECT id, rider_id, driver_id, ride_status, requested_at, matching_at, matched_at, accepted_at FROM ride
ORDER BY requested_at
`

func (q *Queries) ListRides(ctx context.Context) ([]Ride, error) {
	rows, err := q.db.Query(ctx, listRides)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ride
	for rows.Next() {
		var i Ride
		if err := rows.Scan(
			&i.ID,
			&i.RiderID,
			&i.DriverID,
			&i.RideStatus,
			&i.RequestedAt,
			&i.MatchingAt,
			&i.MatchedAt,
			&i.AcceptedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRideAccepted = `-- name: UpdateRideAccepted :one
UPDATE ride
SET driver_id = $2,
    ride_status = 'accepted',
    accepted_at = NOW()
WHERE id = $1
    AND ride_status = 'matched'
RETURNING id, rider_id, driver_id, ride_status, requested_at, matching_at, matched_at, accepted_at
`

type UpdateRideAcceptedParams struct {
	ID       pgtype.UUID
	DriverID pgtype.UUID
}

func (q *Queries) UpdateRideAccepted(ctx context.Context, arg UpdateRideAcceptedParams) (Ride, error) {
	row := q.db.QueryRow(ctx, updateRideAccepted, arg.ID, arg.DriverID)
	var i Ride
	err := row.Scan(
		&i.ID,
		&i.RiderID,
		&i.DriverID,
		&i.RideStatus,
		&i.RequestedAt,
		&i.MatchingAt,
		&i.MatchedAt,
		&i.AcceptedAt,
	)
	return i, err
}

const updateRideMatched = `-- name: UpdateRideMatched :one
UPDATE ride
SET ride_status = 'matched',
    matched_at = NOW()
WHERE id = $1
    AND ride_status = 'matching'
RETURNING id, rider_id, driver_id, ride_status, requested_at, matching_at, matched_at, accepted_at
`

func (q *Queries) UpdateRideMatched(ctx context.Context, id pgtype.UUID) (Ride, error) {
	row := q.db.QueryRow(ctx, updateRideMatched, id)
	var i Ride
	err := row.Scan(
		&i.ID,
		&i.RiderID,
		&i.DriverID,
		&i.RideStatus,
		&i.RequestedAt,
		&i.MatchingAt,
		&i.MatchedAt,
		&i.AcceptedAt,
	)
	return i, err
}

const updateRideMatching = `-- name: UpdateRideMatching :one

UPDATE ride
SET ride_status = 'matching',
    matching_at = NOW()
WHERE id = $1
    AND ride_status = 'requested'
RETURNING id, rider_id, driver_id, ride_status, requested_at, matching_at, matched_at, accepted_at
`

// TODO: check if 1) ride exists 2) the correct enum is being inserted
func (q *Queries) UpdateRideMatching(ctx context.Context, id pgtype.UUID) (Ride, error) {
	row := q.db.QueryRow(ctx, updateRideMatching, id)
	var i Ride
	err := row.Scan(
		&i.ID,
		&i.RiderID,
		&i.DriverID,
		&i.RideStatus,
		&i.RequestedAt,
		&i.MatchingAt,
		&i.MatchedAt,
		&i.AcceptedAt,
	)
	return i, err
}

const updateRideStatus = `-- name: UpdateRideStatus :one
UPDATE ride
SET ride_status = $2
WHERE id = $1 
    AND $2::ridestatus IN ('completed', 'cancelled', 'failed', 'in_progress')
RETURNING id, rider_id, driver_id, ride_status, requested_at, matching_at, matched_at, accepted_at
`

type UpdateRideStatusParams struct {
	ID         pgtype.UUID
	RideStatus Ridestatus
}

func (q *Queries) UpdateRideStatus(ctx context.Context, arg UpdateRideStatusParams) (Ride, error) {
	row := q.db.QueryRow(ctx, updateRideStatus, arg.ID, arg.RideStatus)
	var i Ride
	err := row.Scan(
		&i.ID,
		&i.RiderID,
		&i.DriverID,
		&i.RideStatus,
		&i.RequestedAt,
		&i.MatchingAt,
		&i.MatchedAt,
		&i.AcceptedAt,
	)
	return i, err
}
