// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package ridedata

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkDedupEntry = `-- name: CheckDedupEntry :one
SELECT id, ride_id, stream, processed_at FROM deduplication
WHERE ride_id = $1
  AND stream = $2
`

type CheckDedupEntryParams struct {
	RideID pgtype.UUID
	Stream Stream
}

func (q *Queries) CheckDedupEntry(ctx context.Context, arg CheckDedupEntryParams) (Deduplication, error) {
	row := q.db.QueryRow(ctx, checkDedupEntry, arg.RideID, arg.Stream)
	var i Deduplication
	err := row.Scan(
		&i.ID,
		&i.RideID,
		&i.Stream,
		&i.ProcessedAt,
	)
	return i, err
}

const claimOutboxEvent = `-- name: ClaimOutboxEvent :one
UPDATE outbox
SET retrieved_at = NOW()
WHERE id = (
    SELECT id
    FROM outbox
    WHERE published_at IS NULL
    AND (
      retrieved_at IS NULL  -- fresh rows
      OR retrieved_at < NOW() - INTERVAL '1 second' * $1 -- stale / timed out rows
    )
    ORDER BY created_at ASC
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
RETURNING id, ride_id, stream, created_at, retrieved_at, published_at
`

func (q *Queries) ClaimOutboxEvent(ctx context.Context, dollar_1 interface{}) (Outbox, error) {
	row := q.db.QueryRow(ctx, claimOutboxEvent, dollar_1)
	var i Outbox
	err := row.Scan(
		&i.ID,
		&i.RideID,
		&i.Stream,
		&i.CreatedAt,
		&i.RetrievedAt,
		&i.PublishedAt,
	)
	return i, err
}

const createDedupEntry = `-- name: CreateDedupEntry :one
/* 
* Deduplication
*/ 
INSERT INTO deduplication (
    ride_id, stream
) VALUES (
    $1, $2
) ON CONFLICT (
    ride_id, stream
) DO NOTHING
RETURNING id, ride_id, stream, processed_at
`

type CreateDedupEntryParams struct {
	RideID pgtype.UUID
	Stream Stream
}

func (q *Queries) CreateDedupEntry(ctx context.Context, arg CreateDedupEntryParams) (Deduplication, error) {
	row := q.db.QueryRow(ctx, createDedupEntry, arg.RideID, arg.Stream)
	var i Deduplication
	err := row.Scan(
		&i.ID,
		&i.RideID,
		&i.Stream,
		&i.ProcessedAt,
	)
	return i, err
}

const createOutboxEvent = `-- name: CreateOutboxEvent :one
/* 
* Outbox
*/ 
INSERT INTO outbox (
  ride_id, stream
) VALUES (
  $1, $2
) 
RETURNING id, ride_id, stream, created_at, retrieved_at, published_at
`

type CreateOutboxEventParams struct {
	RideID pgtype.UUID
	Stream Stream
}

func (q *Queries) CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (Outbox, error) {
	row := q.db.QueryRow(ctx, createOutboxEvent, arg.RideID, arg.Stream)
	var i Outbox
	err := row.Scan(
		&i.ID,
		&i.RideID,
		&i.Stream,
		&i.CreatedAt,
		&i.RetrievedAt,
		&i.PublishedAt,
	)
	return i, err
}

const createReqDedupEntry = `-- name: CreateReqDedupEntry :one
INSERT INTO requestDedup (
    idempKey
) VALUES (
    $1
) ON CONFLICT (
    idempKey
) DO NOTHING
RETURNING ride_id
`

func (q *Queries) CreateReqDedupEntry(ctx context.Context, idempkey pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createReqDedupEntry, idempkey)
	var ride_id pgtype.UUID
	err := row.Scan(&ride_id)
	return ride_id, err
}

const createRide = `-- name: CreateRide :one
INSERT INTO ride (
  id, rider_id
) VALUES (
  $1, $2
)
RETURNING id, rider_id, driver_id, ride_status, requested_at, accepted_at
`

type CreateRideParams struct {
	ID      pgtype.UUID
	RiderID pgtype.UUID
}

func (q *Queries) CreateRide(ctx context.Context, arg CreateRideParams) (Ride, error) {
	row := q.db.QueryRow(ctx, createRide, arg.ID, arg.RiderID)
	var i Ride
	err := row.Scan(
		&i.ID,
		&i.RiderID,
		&i.DriverID,
		&i.RideStatus,
		&i.RequestedAt,
		&i.AcceptedAt,
	)
	return i, err
}

const deleteRide = `-- name: DeleteRide :exec
DELETE FROM ride
WHERE id = $1
`

func (q *Queries) DeleteRide(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRide, id)
	return err
}

const getRide = `-- name: GetRide :one
/* 
* Ride
*/ 

SELECT id, rider_id, driver_id, ride_status, requested_at, accepted_at FROM ride
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetRide(ctx context.Context, id pgtype.UUID) (Ride, error) {
	row := q.db.QueryRow(ctx, getRide, id)
	var i Ride
	err := row.Scan(
		&i.ID,
		&i.RiderID,
		&i.DriverID,
		&i.RideStatus,
		&i.RequestedAt,
		&i.AcceptedAt,
	)
	return i, err
}

const getStaleRides = `-- name: GetStaleRides :many
/* 
    reconciler Queries
*/
SELECT id, rider_id, driver_id, ride_status, requested_at, accepted_at FROM ride
WHERE ride_status = $1
  AND requested_at < NOW() - INTERVAL '1 second' * $2
`

type GetStaleRidesParams struct {
	RideStatus Ridestatus
	Column2    interface{}
}

func (q *Queries) GetStaleRides(ctx context.Context, arg GetStaleRidesParams) ([]Ride, error) {
	rows, err := q.db.Query(ctx, getStaleRides, arg.RideStatus, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ride
	for rows.Next() {
		var i Ride
		if err := rows.Scan(
			&i.ID,
			&i.RiderID,
			&i.DriverID,
			&i.RideStatus,
			&i.RequestedAt,
			&i.AcceptedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnpublishedOutboxEvents = `-- name: GetUnpublishedOutboxEvents :many
SELECT id, ride_id, stream, created_at, retrieved_at, published_at FROM outbox
WHERE ride_id = ANY($1::uuid[])
  AND stream = 'ride.requested'
  AND published_at IS NULL
`

// DON'T use this during the outbox publishing relay. That's ClaimOutboxEvent
func (q *Queries) GetUnpublishedOutboxEvents(ctx context.Context, rideIds []pgtype.UUID) ([]Outbox, error) {
	rows, err := q.db.Query(ctx, getUnpublishedOutboxEvents, rideIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Outbox
	for rows.Next() {
		var i Outbox
		if err := rows.Scan(
			&i.ID,
			&i.RideID,
			&i.Stream,
			&i.CreatedAt,
			&i.RetrievedAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertRedDedupRide = `-- name: InsertRedDedupRide :exec
UPDATE requestDedup 
SET  ride_id = $2
WHERE idempKey = $1
`

type InsertRedDedupRideParams struct {
	Idempkey pgtype.UUID
	RideID   pgtype.UUID
}

func (q *Queries) InsertRedDedupRide(ctx context.Context, arg InsertRedDedupRideParams) error {
	_, err := q.db.Exec(ctx, insertRedDedupRide, arg.Idempkey, arg.RideID)
	return err
}

const listRides = `-- name: ListRides :many
SELECT id, rider_id, driver_id, ride_status, requested_at, accepted_at FROM ride
ORDER BY requested_at
`

func (q *Queries) ListRides(ctx context.Context) ([]Ride, error) {
	rows, err := q.db.Query(ctx, listRides)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ride
	for rows.Next() {
		var i Ride
		if err := rows.Scan(
			&i.ID,
			&i.RiderID,
			&i.DriverID,
			&i.RideStatus,
			&i.RequestedAt,
			&i.AcceptedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDedupProcessed = `-- name: SetDedupProcessed :exec
UPDATE deduplication 
SET processed_at = NOW()
WHERE ride_id = $1 
    AND stream = $2
`

type SetDedupProcessedParams struct {
	RideID pgtype.UUID
	Stream Stream
}

// don't currently use this
func (q *Queries) SetDedupProcessed(ctx context.Context, arg SetDedupProcessedParams) error {
	_, err := q.db.Exec(ctx, setDedupProcessed, arg.RideID, arg.Stream)
	return err
}

const setOutboxPublished = `-- name: SetOutboxPublished :exec
UPDATE outbox 
SET published_at = NOW()
WHERE id = $1
`

func (q *Queries) SetOutboxPublished(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, setOutboxPublished, id)
	return err
}

const setRideAccepted = `-- name: SetRideAccepted :one

UPDATE ride
SET driver_id = $2,
    ride_status = 'accepted',
    accepted_at = NOW()
WHERE id = $1
    AND ride_status = 'requested'
RETURNING id, rider_id, driver_id, ride_status, requested_at, accepted_at
`

type SetRideAcceptedParams struct {
	ID       pgtype.UUID
	DriverID pgtype.UUID
}

// -- name: UpdateRideStatus :one
// UPDATE ride
// SET ride_status = $2
// WHERE id = $1
//
//	AND $2::ridestatus IN ('completed', 'cancelled', 'failed', 'in_progress')
//
// RETURNING *;
// -- TODO: check if 1) ride exists 2) the correct enum is being inserted
func (q *Queries) SetRideAccepted(ctx context.Context, arg SetRideAcceptedParams) (Ride, error) {
	row := q.db.QueryRow(ctx, setRideAccepted, arg.ID, arg.DriverID)
	var i Ride
	err := row.Scan(
		&i.ID,
		&i.RiderID,
		&i.DriverID,
		&i.RideStatus,
		&i.RequestedAt,
		&i.AcceptedAt,
	)
	return i, err
}
