// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: ride.proto

package ride

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Even if unimplemented, make sure these are as granular as possible to avoid silent fails
type RideStatus int32

const (
	RideStatus_RIDE_STATUS_UNSPECIFIED RideStatus = 0
	RideStatus_RIDE_STATUS_REQUESTED   RideStatus = 1 // Rider requested and is awaiting matching
	RideStatus_RIDE_STATUS_MATCHING    RideStatus = 2 // Requested-Matching are split to account for failures
	RideStatus_RIDE_STATUS_MATCHED     RideStatus = 3 // Driver matched, awaiting acceptance (10s TTL)
	RideStatus_RIDE_STATUS_ACCEPTED    RideStatus = 4 // Driver accepted. Implicit: en route to pickup, so stream driver location
	RideStatus_RIDE_STATUS_IN_PROGRESS RideStatus = 5 // Rider picked up
	RideStatus_RIDE_STATUS_COMPLETED   RideStatus = 6
	RideStatus_RIDE_STATUS_CANCELLED   RideStatus = 7
	RideStatus_RIDE_STATUS_FAILED      RideStatus = 8
)

// Enum value maps for RideStatus.
var (
	RideStatus_name = map[int32]string{
		0: "RIDE_STATUS_UNSPECIFIED",
		1: "RIDE_STATUS_REQUESTED",
		2: "RIDE_STATUS_MATCHING",
		3: "RIDE_STATUS_MATCHED",
		4: "RIDE_STATUS_ACCEPTED",
		5: "RIDE_STATUS_IN_PROGRESS",
		6: "RIDE_STATUS_COMPLETED",
		7: "RIDE_STATUS_CANCELLED",
		8: "RIDE_STATUS_FAILED",
	}
	RideStatus_value = map[string]int32{
		"RIDE_STATUS_UNSPECIFIED": 0,
		"RIDE_STATUS_REQUESTED":   1,
		"RIDE_STATUS_MATCHING":    2,
		"RIDE_STATUS_MATCHED":     3,
		"RIDE_STATUS_ACCEPTED":    4,
		"RIDE_STATUS_IN_PROGRESS": 5,
		"RIDE_STATUS_COMPLETED":   6,
		"RIDE_STATUS_CANCELLED":   7,
		"RIDE_STATUS_FAILED":      8,
	}
)

func (x RideStatus) Enum() *RideStatus {
	p := new(RideStatus)
	*p = x
	return p
}

func (x RideStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RideStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_ride_proto_enumTypes[0].Descriptor()
}

func (RideStatus) Type() protoreflect.EnumType {
	return &file_ride_proto_enumTypes[0]
}

func (x RideStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RideStatus.Descriptor instead.
func (RideStatus) EnumDescriptor() ([]byte, []int) {
	return file_ride_proto_rawDescGZIP(), []int{0}
}

type Ride struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	RiderId       *string                `protobuf:"bytes,2,opt,name=rider_id,json=riderId" json:"rider_id,omitempty"`
	DriverId      *string                `protobuf:"bytes,3,opt,name=driver_id,json=driverId" json:"driver_id,omitempty"`
	RideStatus    *RideStatus            `protobuf:"varint,4,opt,name=ride_status,json=rideStatus,enum=ride.RideStatus" json:"ride_status,omitempty"`
	RequestedAt   *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=requested_at,json=requestedAt" json:"requested_at,omitempty"`
	MatchingAt    *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=matching_at,json=matchingAt" json:"matching_at,omitempty"`
	MatchedAt     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=matched_at,json=matchedAt" json:"matched_at,omitempty"`
	AcceptedAt    *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=accepted_at,json=acceptedAt" json:"accepted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ride) Reset() {
	*x = Ride{}
	mi := &file_ride_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ride) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ride) ProtoMessage() {}

func (x *Ride) ProtoReflect() protoreflect.Message {
	mi := &file_ride_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ride.ProtoReflect.Descriptor instead.
func (*Ride) Descriptor() ([]byte, []int) {
	return file_ride_proto_rawDescGZIP(), []int{0}
}

func (x *Ride) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *Ride) GetRiderId() string {
	if x != nil && x.RiderId != nil {
		return *x.RiderId
	}
	return ""
}

func (x *Ride) GetDriverId() string {
	if x != nil && x.DriverId != nil {
		return *x.DriverId
	}
	return ""
}

func (x *Ride) GetRideStatus() RideStatus {
	if x != nil && x.RideStatus != nil {
		return *x.RideStatus
	}
	return RideStatus_RIDE_STATUS_UNSPECIFIED
}

func (x *Ride) GetRequestedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RequestedAt
	}
	return nil
}

func (x *Ride) GetMatchingAt() *timestamppb.Timestamp {
	if x != nil {
		return x.MatchingAt
	}
	return nil
}

func (x *Ride) GetMatchedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.MatchedAt
	}
	return nil
}

func (x *Ride) GetAcceptedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AcceptedAt
	}
	return nil
}

type RequestRideRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IdempotencyKey *string                `protobuf:"bytes,1,opt,name=idempotency_key,json=idempotencyKey" json:"idempotency_key,omitempty"`
	RiderId        *string                `protobuf:"bytes,2,opt,name=rider_id,json=riderId" json:"rider_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RequestRideRequest) Reset() {
	*x = RequestRideRequest{}
	mi := &file_ride_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestRideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestRideRequest) ProtoMessage() {}

func (x *RequestRideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ride_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestRideRequest.ProtoReflect.Descriptor instead.
func (*RequestRideRequest) Descriptor() ([]byte, []int) {
	return file_ride_proto_rawDescGZIP(), []int{1}
}

func (x *RequestRideRequest) GetIdempotencyKey() string {
	if x != nil && x.IdempotencyKey != nil {
		return *x.IdempotencyKey
	}
	return ""
}

func (x *RequestRideRequest) GetRiderId() string {
	if x != nil && x.RiderId != nil {
		return *x.RiderId
	}
	return ""
}

type RequestRideResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ride          *Ride                  `protobuf:"bytes,1,opt,name=ride" json:"ride,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestRideResponse) Reset() {
	*x = RequestRideResponse{}
	mi := &file_ride_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestRideResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestRideResponse) ProtoMessage() {}

func (x *RequestRideResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ride_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestRideResponse.ProtoReflect.Descriptor instead.
func (*RequestRideResponse) Descriptor() ([]byte, []int) {
	return file_ride_proto_rawDescGZIP(), []int{2}
}

func (x *RequestRideResponse) GetRide() *Ride {
	if x != nil {
		return x.Ride
	}
	return nil
}

type GetRideRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RideId        *string                `protobuf:"bytes,1,opt,name=ride_id,json=rideId" json:"ride_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRideRequest) Reset() {
	*x = GetRideRequest{}
	mi := &file_ride_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRideRequest) ProtoMessage() {}

func (x *GetRideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ride_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRideRequest.ProtoReflect.Descriptor instead.
func (*GetRideRequest) Descriptor() ([]byte, []int) {
	return file_ride_proto_rawDescGZIP(), []int{3}
}

func (x *GetRideRequest) GetRideId() string {
	if x != nil && x.RideId != nil {
		return *x.RideId
	}
	return ""
}

type GetRideResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ride          *Ride                  `protobuf:"bytes,1,opt,name=ride" json:"ride,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRideResponse) Reset() {
	*x = GetRideResponse{}
	mi := &file_ride_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRideResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRideResponse) ProtoMessage() {}

func (x *GetRideResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ride_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRideResponse.ProtoReflect.Descriptor instead.
func (*GetRideResponse) Descriptor() ([]byte, []int) {
	return file_ride_proto_rawDescGZIP(), []int{4}
}

func (x *GetRideResponse) GetRide() *Ride {
	if x != nil {
		return x.Ride
	}
	return nil
}

type UpdateRideStatusRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IdempotencyKey *string                `protobuf:"bytes,1,opt,name=idempotency_key,json=idempotencyKey" json:"idempotency_key,omitempty"`
	RideId         *string                `protobuf:"bytes,2,opt,name=ride_id,json=rideId" json:"ride_id,omitempty"`
	RideStatus     *RideStatus            `protobuf:"varint,3,opt,name=ride_status,json=rideStatus,enum=ride.RideStatus" json:"ride_status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateRideStatusRequest) Reset() {
	*x = UpdateRideStatusRequest{}
	mi := &file_ride_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRideStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRideStatusRequest) ProtoMessage() {}

func (x *UpdateRideStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ride_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRideStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateRideStatusRequest) Descriptor() ([]byte, []int) {
	return file_ride_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateRideStatusRequest) GetIdempotencyKey() string {
	if x != nil && x.IdempotencyKey != nil {
		return *x.IdempotencyKey
	}
	return ""
}

func (x *UpdateRideStatusRequest) GetRideId() string {
	if x != nil && x.RideId != nil {
		return *x.RideId
	}
	return ""
}

func (x *UpdateRideStatusRequest) GetRideStatus() RideStatus {
	if x != nil && x.RideStatus != nil {
		return *x.RideStatus
	}
	return RideStatus_RIDE_STATUS_UNSPECIFIED
}

type UpdateRideStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ride          *Ride                  `protobuf:"bytes,1,opt,name=ride" json:"ride,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRideStatusResponse) Reset() {
	*x = UpdateRideStatusResponse{}
	mi := &file_ride_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRideStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRideStatusResponse) ProtoMessage() {}

func (x *UpdateRideStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ride_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRideStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateRideStatusResponse) Descriptor() ([]byte, []int) {
	return file_ride_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateRideStatusResponse) GetRide() *Ride {
	if x != nil {
		return x.Ride
	}
	return nil
}

var File_ride_proto protoreflect.FileDescriptor

const file_ride_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"ride.proto\x12\x04ride\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf5\x02\n" +
	"\x04Ride\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\brider_id\x18\x02 \x01(\tR\ariderId\x12\x1b\n" +
	"\tdriver_id\x18\x03 \x01(\tR\bdriverId\x121\n" +
	"\vride_status\x18\x04 \x01(\x0e2\x10.ride.RideStatusR\n" +
	"rideStatus\x12=\n" +
	"\frequested_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\vrequestedAt\x12;\n" +
	"\vmatching_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"matchingAt\x129\n" +
	"\n" +
	"matched_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tmatchedAt\x12;\n" +
	"\vaccepted_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"acceptedAt\"X\n" +
	"\x12RequestRideRequest\x12'\n" +
	"\x0fidempotency_key\x18\x01 \x01(\tR\x0eidempotencyKey\x12\x19\n" +
	"\brider_id\x18\x02 \x01(\tR\ariderId\"5\n" +
	"\x13RequestRideResponse\x12\x1e\n" +
	"\x04ride\x18\x01 \x01(\v2\n" +
	".ride.RideR\x04ride\")\n" +
	"\x0eGetRideRequest\x12\x17\n" +
	"\aride_id\x18\x01 \x01(\tR\x06rideId\"1\n" +
	"\x0fGetRideResponse\x12\x1e\n" +
	"\x04ride\x18\x01 \x01(\v2\n" +
	".ride.RideR\x04ride\"\x8e\x01\n" +
	"\x17UpdateRideStatusRequest\x12'\n" +
	"\x0fidempotency_key\x18\x01 \x01(\tR\x0eidempotencyKey\x12\x17\n" +
	"\aride_id\x18\x02 \x01(\tR\x06rideId\x121\n" +
	"\vride_status\x18\x03 \x01(\x0e2\x10.ride.RideStatusR\n" +
	"rideStatus\":\n" +
	"\x18UpdateRideStatusResponse\x12\x1e\n" +
	"\x04ride\x18\x01 \x01(\v2\n" +
	".ride.RideR\x04ride*\xfc\x01\n" +
	"\n" +
	"RideStatus\x12\x1b\n" +
	"\x17RIDE_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15RIDE_STATUS_REQUESTED\x10\x01\x12\x18\n" +
	"\x14RIDE_STATUS_MATCHING\x10\x02\x12\x17\n" +
	"\x13RIDE_STATUS_MATCHED\x10\x03\x12\x18\n" +
	"\x14RIDE_STATUS_ACCEPTED\x10\x04\x12\x1b\n" +
	"\x17RIDE_STATUS_IN_PROGRESS\x10\x05\x12\x19\n" +
	"\x15RIDE_STATUS_COMPLETED\x10\x06\x12\x19\n" +
	"\x15RIDE_STATUS_CANCELLED\x10\a\x12\x16\n" +
	"\x12RIDE_STATUS_FAILED\x10\b2\xe2\x01\n" +
	"\vRideService\x12D\n" +
	"\vRequestRide\x12\x18.ride.RequestRideRequest\x1a\x19.ride.RequestRideResponse\"\x00\x128\n" +
	"\aGetRide\x12\x14.ride.GetRideRequest\x1a\x15.ride.GetRideResponse\"\x00\x12S\n" +
	"\x10UpdateRideStatus\x12\x1d.ride.UpdateRideStatusRequest\x1a\x1e.ride.UpdateRideStatusResponse\"\x00BBZ@github.com/beedsneeds/resilient-distributed-rideshare/proto/rideb\beditionsp\xe8\a"

var (
	file_ride_proto_rawDescOnce sync.Once
	file_ride_proto_rawDescData []byte
)

func file_ride_proto_rawDescGZIP() []byte {
	file_ride_proto_rawDescOnce.Do(func() {
		file_ride_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ride_proto_rawDesc), len(file_ride_proto_rawDesc)))
	})
	return file_ride_proto_rawDescData
}

var file_ride_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ride_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_ride_proto_goTypes = []any{
	(RideStatus)(0),                  // 0: ride.RideStatus
	(*Ride)(nil),                     // 1: ride.Ride
	(*RequestRideRequest)(nil),       // 2: ride.RequestRideRequest
	(*RequestRideResponse)(nil),      // 3: ride.RequestRideResponse
	(*GetRideRequest)(nil),           // 4: ride.GetRideRequest
	(*GetRideResponse)(nil),          // 5: ride.GetRideResponse
	(*UpdateRideStatusRequest)(nil),  // 6: ride.UpdateRideStatusRequest
	(*UpdateRideStatusResponse)(nil), // 7: ride.UpdateRideStatusResponse
	(*timestamppb.Timestamp)(nil),    // 8: google.protobuf.Timestamp
}
var file_ride_proto_depIdxs = []int32{
	0,  // 0: ride.Ride.ride_status:type_name -> ride.RideStatus
	8,  // 1: ride.Ride.requested_at:type_name -> google.protobuf.Timestamp
	8,  // 2: ride.Ride.matching_at:type_name -> google.protobuf.Timestamp
	8,  // 3: ride.Ride.matched_at:type_name -> google.protobuf.Timestamp
	8,  // 4: ride.Ride.accepted_at:type_name -> google.protobuf.Timestamp
	1,  // 5: ride.RequestRideResponse.ride:type_name -> ride.Ride
	1,  // 6: ride.GetRideResponse.ride:type_name -> ride.Ride
	0,  // 7: ride.UpdateRideStatusRequest.ride_status:type_name -> ride.RideStatus
	1,  // 8: ride.UpdateRideStatusResponse.ride:type_name -> ride.Ride
	2,  // 9: ride.RideService.RequestRide:input_type -> ride.RequestRideRequest
	4,  // 10: ride.RideService.GetRide:input_type -> ride.GetRideRequest
	6,  // 11: ride.RideService.UpdateRideStatus:input_type -> ride.UpdateRideStatusRequest
	3,  // 12: ride.RideService.RequestRide:output_type -> ride.RequestRideResponse
	5,  // 13: ride.RideService.GetRide:output_type -> ride.GetRideResponse
	7,  // 14: ride.RideService.UpdateRideStatus:output_type -> ride.UpdateRideStatusResponse
	12, // [12:15] is the sub-list for method output_type
	9,  // [9:12] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_ride_proto_init() }
func file_ride_proto_init() {
	if File_ride_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ride_proto_rawDesc), len(file_ride_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ride_proto_goTypes,
		DependencyIndexes: file_ride_proto_depIdxs,
		EnumInfos:         file_ride_proto_enumTypes,
		MessageInfos:      file_ride_proto_msgTypes,
	}.Build()
	File_ride_proto = out.File
	file_ride_proto_goTypes = nil
	file_ride_proto_depIdxs = nil
}
