// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package riderdata

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type Riderstatus string

const (
	RiderstatusAvailable Riderstatus = "available"
	RiderstatusOnaride   Riderstatus = "on a ride"
)

func (e *Riderstatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Riderstatus(s)
	case string:
		*e = Riderstatus(s)
	default:
		return fmt.Errorf("unsupported scan type for Riderstatus: %T", src)
	}
	return nil
}

type NullRiderstatus struct {
	Riderstatus Riderstatus
	Valid       bool // Valid is true if Riderstatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRiderstatus) Scan(value interface{}) error {
	if value == nil {
		ns.Riderstatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Riderstatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRiderstatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Riderstatus), nil
}

type Rider struct {
	ID     pgtype.UUID
	Name   string
	Status Riderstatus
}
