// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package riderdata

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRider = `-- name: CreateRider :one
INSERT INTO rider (
    name
) VALUES (
  $1
)
RETURNING id, name, status
`

func (q *Queries) CreateRider(ctx context.Context, name string) (Rider, error) {
	row := q.db.QueryRow(ctx, createRider, name)
	var i Rider
	err := row.Scan(&i.ID, &i.Name, &i.Status)
	return i, err
}

const deleteRider = `-- name: DeleteRider :exec
DELETE FROM rider 
WHERE id = $1
`

func (q *Queries) DeleteRider(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRider, id)
	return err
}

const getRandomAvailableRider = `-- name: GetRandomAvailableRider :one
SELECT id, name, status FROM rider
WHERE status = 'available'
ORDER BY RANDOM()
LIMIT 1
`

func (q *Queries) GetRandomAvailableRider(ctx context.Context) (Rider, error) {
	row := q.db.QueryRow(ctx, getRandomAvailableRider)
	var i Rider
	err := row.Scan(&i.ID, &i.Name, &i.Status)
	return i, err
}

const getRider = `-- name: GetRider :one
/* 
* Rider
*/ 

SELECT id, name, status FROM rider
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetRider(ctx context.Context, id pgtype.UUID) (Rider, error) {
	row := q.db.QueryRow(ctx, getRider, id)
	var i Rider
	err := row.Scan(&i.ID, &i.Name, &i.Status)
	return i, err
}

const listRiders = `-- name: ListRiders :many
SELECT id, name, status FROM rider
ORDER BY name
`

func (q *Queries) ListRiders(ctx context.Context) ([]Rider, error) {
	rows, err := q.db.Query(ctx, listRiders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Rider
	for rows.Next() {
		var i Rider
		if err := rows.Scan(&i.ID, &i.Name, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRiderStatus = `-- name: UpdateRiderStatus :exec
UPDATE rider
SET status = $2
WHERE id = $1
`

type UpdateRiderStatusParams struct {
	ID     pgtype.UUID
	Status Riderstatus
}

func (q *Queries) UpdateRiderStatus(ctx context.Context, arg UpdateRiderStatusParams) error {
	_, err := q.db.Exec(ctx, updateRiderStatus, arg.ID, arg.Status)
	return err
}
